# Generated by Django 4.0.1 on 2024-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_max_experience_job_min_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_experience',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
